baseURL = 'https://evolvingcomplexity.co.uk/'
relativeURLs = true
languageCode = 'en-gb'
title = 'Evolving Complexity'
theme = 'paper'

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[permalinks]
    posts = "/:year/:month/:title/"
    page = "/:title/"

[author]
    name = 'Ryan Kerry'

[params]
    color = 'linen'

    paginate = 2

    disableHLJS = false
    monoDarkIcon = true

    description = 'Include something in here'

    avatar = 'GRAVATAR_EMAIL'
    name = 'Evolving Complexity'
    bio = "Hey 👋 - I'm Ryan and I am currently a Senior Director of Software Engineering at Unity. I blog here semi-frequently about engineering leadership, management, technology, and my scuba diving adventures."

    # --------------------------------------
    # social channels
    # --------------------------------------
    twitter = 'YOUR_TWITTER_ID'
    github = 'Ryank90'
    instagram = 'YOUR_INSTAGRAM_ID'

[[menu.main]]
    identifier = "posts"
    name = "Articles"
    url = "/posts/"
    weight = 1

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2