# baseURL = 'https://www.evolvingcomplexities.com/'
relativeURLs = true
languageCode = 'en-gb'
title = 'Evolving Complexities'
theme = 'paper'

[permalinks]
    post = "/posts/:title/"
    page = "/:title/"

[author]
    name = 'ryan kerry'

[params]
    color = 'linen'

    paginate = 5

    disableHLJS = false
    monoDarkIcon = true

    avatar = 'GRAVATAR_EMAIL'
    name = 'Evolving Complexities'
    bio = 'Ryan Kerry introduction to some random commentary here...'

    # --------------------------------------
    # social channels
    # --------------------------------------
    twitter = 'YOUR_TWITTER_ID'
    github = 'YOUR_GITHUB_ID'
    instagram = 'YOUR_INSTAGRAM_ID'


[[menu.main]]
    identifier = "posts"
    name = "Archive"
    url = "/posts/"
    weight = 1

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2